package:
  name: qa-dkrz
  version: '0.6.7'

build:
#  number: 31

  number: 63

source:
#   git_url: https://github.com/IS-ENES-Data/QA-DKRZ.git
#   git_tag: master
  git_url: ../../.git
#  git_tag: develop
  git_tag: master

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libnetcdf 4.4.*
    - jpeg 9b
    - zlib
    - udunits2
    - libuuid
    - expat
    - curl
    - libgcc
  run:
    - libnetcdf 4.4.*
    - jpeg 9b
    - zlib
    - udunits2
    - libuuid
    - expat
    - curl
    - libgcc
    - git
#test:
#  commands:
#    - dkrz-cf-checker -h
#    - qa-dkrz -h

about:
  home: http://qa-dkrz.readthedocs.org/en/latest/
  summary: 'Quality Assurance checker of meta-data in climate data sets (NetCDF files) for CF compliance checks and CMIP5/6 as well as CORDEX projects conventions.'
  license: Copyright DKRZ
